# Generated by Django 2.2 on 2019-11-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_name', to='products.Product')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_price', to='products.Product')),
                ('product_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_quantity', to='products.Product')),
            ],
        ),
    ]
