# Generated by Django 2.2 on 2020-02-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200203_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_quantity',
        ),
    ]
