# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_invoice_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
