# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20181119_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Created_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='Invoice_date',
            new_name='invoice_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='Invoice_from',
            new_name='invoice_from',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='Invoice_product',
            new_name='invoice_product',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='Invoice_to',
            new_name='invoice_to',
        ),
    ]
