# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20181119_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
