# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
