# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181124_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
