# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_stock',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
